### ISSUE TITLE
Update dependencies: Warning RedisCache.php(135): Deprecated - Function Redis::delete() is deprecated 

### ISSUE THREAD

**Issue by tsteur** [matomo-org/component-cache#23]
See https://github.com/matomo-org/matomo/issues/15067#issuecomment-547132608

Instead of delete it should call the `del` method I reckon. For this we would probably need to update the doctrine dependency see https://github.com/doctrine/cache/blob/v1.8.1/lib/Doctrine/Common/Cache/RedisCache.php#L126

**Comment by peter279k** [comment]
@tsteur, to resolve this issue, it should upgrade the `doctrine/cache` to `1.8` version at least.

But the `doctrine/cache` version requires `php-7.1` at least.

I think it should drop the `php-5.x` and `php-7.0` versions if we want to resolve this issue.

**Comment by peter279k** [comment]
The references are available here:

- https://github.com/doctrine/cache/blob/1.8.x/composer.json
- https://github.com/doctrine/cache/blob/1.8.x/lib/Doctrine/Common/Cache/RedisCache.php#L134

**Comment by peter279k** [comment]
I think this issue should be closed since the PR #24 is merged.

**Comment by leftmostlane** [comment]
Seems like this was fixed however not included in 3.13.1 even though the README says it was.   Specifically, in unzip Matomo 3.13.1 and view the file: "Common/Cache/RedisCache.php" includes "$this->redis->delete" and not the corrected code: "$this->redis->del".  Perhaps an incorrect branch of "cache" was used to build Matomo 3.13.1?
